### ISSUE TITLE
请问我用node 启动web.js 的时候提示找不到 mime 是为什么呢?

### ISSUE THREAD

**Issue by yestodayHadRain** [dumingxin/jenkinsNode#1]
```
node web.js 

internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module 'mime'
Require stack:
- /var/jenkins_home/QrCodeServer/jenkinsNode/web.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/jenkins_home/QrCodeServer/jenkinsNode/web.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/jenkins_home/QrCodeServer/jenkinsNode/web.js' ]
}

```

**Comment by dumingxin** [comment]
应该是缺少模块，执行npm install mime安装试一下

**Comment by yestodayHadRain** [comment]
谢谢解答
